version: '3'
services:

### Applications Code Container #############################

    php7:
      build: ./containers/php7
      depends_on:
        - postgres
      volumes:
        - ${APPLICATION}:/var/www/html

    nginx: # php-fpmにリバースプロキシする
      build: ./containers/nginx
      depends_on:
        - php7
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./logs/nginx:/var/log/nginx
        - ./containers/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${APPLICATION}:/var/www/html

    postgres:
      build: ./containers/postgres
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    npm: # npmコマンドを実行するときに都度実行
      build: ./containers/npm
      volumes:
        - ${APPLICATION}:/var/www/html

